### ISSUE TITLE
.env dates

### ISSUE THREAD

**Issue by Noisk8** [Ritavdas/Netflix_Clone#1]
Hello, what data should I put in the .env,  How do I manage the rest of the .env data?

DATABASE_URL=
NEXTAUTH_JWT_SECRET="NEXT-JWT-SECRET"
NEXTAUTH_SECRET="NEXT-SECRET"
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_ID=
GITHUB_SECRET=

**Comment by Ritavdas** [comment]
In a `.env` file, you store environment variables that are used to configure your application. I'll explain each variable and what data you should put in them:

1. `DATABASE_URL`: This is the connection string to your database. It should include the database type, username, password, host, port, and database name. For example, if you're using a PostgreSQL database, it might look like:
```
DATABASE_URL=postgres://user:password@localhost:5432/mydatabasename
```

2. `NEXTAUTH_JWT_SECRET`: This is a secret used to sign JSON Web Tokens (JWTs) for authentication. It should be a long, random, and secure string. You can generate one using an online tool or a password manager.

3. `NEXTAUTH_SECRET`: This is another secret used by NextAuth.js for signing cookies and tokens. It should also be a long, random, and secure string, different from `NEXTAUTH_JWT_SECRET`.

4. `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET`: These are the credentials for Google OAuth. To get these, you need to create a new project in the Google Developer Console, enable the Google API, and set up an OAuth 2.0 client ID. The `GOOGLE_CLIENT_ID` will be the "Client ID" and the `GOOGLE_CLIENT_SECRET` will be the "Client Secret" provided by Google.

5. `GITHUB_ID` and `GITHUB_SECRET`: These are the credentials for GitHub OAuth. To get these, you need to create a new OAuth App in your GitHub account settings. The `GITHUB_ID` will be the "Client ID" and the `GITHUB_SECRET` will be the "Client Secret" provided by GitHub.

**Comment by Noisk8** [comment]
thanks
